/** Fixed composite contract assertions; generation is supplied by the caller. */
import assert from 'node:assert/strict';
import {controlId,initialPanelState} from '../../src/compiler.mjs';
import {checkPanelEditProposal} from '../../src/edit-planning.mjs';
export function createCompositeAcceptanceCases({flat,field,find,button,generate:actualGenerate}) {
const setEnd=async(a,b,label)=>{const r=find(b,label);await a.focus(b,r);await a.page.keyboard.press('End');assert.equal((await a.state())[r.bind],field(b,r).max);};
const setSelect=async(a,b,label,key)=>{const r=find(b,label);await a.focus(b,r);await a.page.keyboard.press(key);return (await a.state())[r.bind];};
const scopedReset=async(a,b,label,affected)=>{const before=await a.state();await a.click(b,button(b,label));const expected={...before};for(const name of affected){const r=find(b,name);expected[r.bind]=field(b,r).initial;}assert.deepEqual(await a.state(),expected);a.pass('reset-'+label+'-exact-scope');};
const cases={
 COM01:async a=>{
  const b=await actualGenerate(a);assert.deepEqual(b.spec.tabs.pages.map(p=>p.label),['声音','显示','操作']);assert.equal(b.spec.layout.maxHeight,320);assert.equal(flat(b).length,14);
  for(const [label,initial,min,max]of [['主音量',70,0,100],['音乐音量',30,0,100],['音效音量',40,0,100],['亮度',60,0,100],['灵敏度',5,1,10]]){const r=find(b,label);assert.equal(r.kind,'slider');const f=field(b,r);assert.deepEqual([f.initial,f.min,f.max,f.step],[initial,min,max,1]);}
  for(const [label,initial]of [['静音',false],['全屏',true],['垂直同步',false],['反转视角',false]])assert.equal(field(b,find(b,label)).initial,initial);
  for(const [label,options,initial]of [['输出设备',['扬声器','耳机'],'扬声器'],['画质',['低','中','高'],'高']]){const f=field(b,find(b,label));assert.deepEqual(f.options.map(o=>o.label),options);assert.equal(f.options.find(o=>o.id===f.initial).label,initial);}
  for(const [label,fields]of [['恢复声音',['主音量','音乐音量','音效音量','静音','输出设备']],['恢复显示',['亮度','画质','全屏','垂直同步']],['恢复操作',['灵敏度','反转视角']]]){const action=button(b,label).action;assert.equal(action.kind,'reset-initial');assert.deepEqual([...action.fields].sort(),fields.map(n=>find(b,n).bind).sort());}
  a.pass('three-pages-all-facts-options-and-scoped-actions');
  for(const label of ['主音量','音乐音量','音效音量'])await setEnd(a,b,label);await a.click(b,find(b,'静音'));const output=await setSelect(a,b,'输出设备','ArrowDown');assert.equal(field(b,find(b,'输出设备')).options.find(o=>o.id===output).label,'耳机');const audio=await a.state();
  await a.choosePage(b,1);await setEnd(a,b,'亮度');await a.click(b,find(b,'全屏'));await scopedReset(a,b,'恢复显示',['亮度','画质','全屏','垂直同步']);for(const label of ['主音量','音乐音量','音效音量','静音','输出设备'])assert.equal((await a.state())[find(b,label).bind],audio[find(b,label).bind]);
  await a.choosePage(b,2);await setEnd(a,b,'灵敏度');await a.click(b,find(b,'反转视角'));await scopedReset(a,b,'恢复操作',['灵敏度','反转视角']);
  await a.choosePage(b,0);await a.focus(b,find(b,'输出设备'));await a.page.keyboard.press('Enter');const inspected=await a.inspect(),select=inspected.nodes.find(n=>n.id===controlId(b.spec.id,find(b,'输出设备').id));assert(select.popupOpen);const scroll=inspected.nodes.find(n=>n.id===b.spec.id+'.page.'+b.spec.tabs.pages[0].id);assert(scroll&&scroll.value.y>0);await a.choosePage(b,1);assert(!(await a.inspect()).nodes.find(n=>n.id===select.id).popupOpen);await a.choosePage(b,0);assert.equal((await a.inspect()).nodes.find(n=>n.id===scroll.id).value.y,scroll.value.y);a.pass('independent-scroll-retained-popup-closes-on-page-change');
  await scopedReset(a,b,'恢复声音',['主音量','音乐音量','音效音量','静音','输出设备']);assert.deepEqual(await a.state(),initialPanelState(b.spec));await a.exportCheck();
 },
 COM02:async a=>{
  const b=await actualGenerate(a);assert.deepEqual(b.spec.tabs.pages.map(p=>p.label),['基本信息','补充信息']);assert.equal(flat(b).length,4);const role=find(b,'角色名'),declaration=find(b,'角色宣言'),submit=button(b,'确认'),cancel=button(b,'取消');
  for(const [r,limit,required,min,placeholder]of [[role,12,true,2,'请输入角色名'],[declaration,30,false,0,'写下角色宣言']]){assert.equal(r.kind,'input');assert.deepEqual([field(b,r).initial,field(b,r).maxLength,r.validation.required,r.validation.minLength,r.placeholder,r.inputType,r.readOnly],['',limit,required,min,placeholder,'text',false]);}
  assert.equal(submit.action.kind,'submit');assert.deepEqual([...submit.action.fields].sort(),[role.bind,declaration.bind].sort());assert.equal(cancel.action.kind,'emit');a.pass('cross-page-input-validation-and-submit-scope');
  await a.type(b,role,'蓝');await a.choosePage(b,1);let nodes=(await a.inspect()).nodes;assert.equal(nodes.find(n=>n.id===controlId(b.spec.id,submit.id)).enabled,false);const count=(await a.events()).length;const node=nodes.find(n=>n.id===controlId(b.spec.id,submit.id)),canvas=a.page.locator('#canvas-host canvas'),rect=await canvas.boundingBox();await a.page.mouse.click(rect.x+(node.bounds.x+node.bounds.width/2)*rect.width/b.spec.canvas.width,rect.y+(node.bounds.y+node.bounds.height/2)*rect.height/b.spec.canvas.height);assert.equal((await a.events()).length,count);a.pass('hidden-page-invalid-role-blocks-submit-without-event');
  await a.type(b,declaration,'勇敢前行😀');await a.choosePage(b,0);assert.equal((await a.state())[declaration.bind],'勇敢前行😀');await a.type(b,role,'小蓝莓');await a.choosePage(b,1);assert.equal((await a.state())[role.bind],'小蓝莓');await a.click(b,submit);let event=(await a.events()).at(-1);assert.equal(event.action,'submit');assert.deepEqual(event.values,{[role.bind]:'小蓝莓',[declaration.bind]:'勇敢前行😀'});assert.deepEqual(event.state,await a.state());a.pass('visible-confirm-submits-both-pages-and-retains-input');
  const before=await a.state();await a.click(b,cancel);assert.deepEqual(await a.state(),before);assert.equal((await a.events()).at(-1).action,'emit');a.pass('cancel-keeps-text-and-selected-page');
  const text='角色名创作默认值改为测试名，角色宣言最大长度改为40，保留当前输入和其他全部配置。';await a.page.locator('#edit-request-text').fill(text);await a.advanced();await a.page.locator('#prepare-edit-context').click();await a.idle();const context=await a.page.evaluate(()=>window.panelWorkbench.editSnapshot().context);const operations=[{op:'set-state-initial',fieldId:role.bind,value:'测试名'},{op:'set-input-properties',rowId:declaration.id,placeholder:declaration.placeholder,inputType:declaration.inputType,readOnly:declaration.readOnly,maxLength:40,validation:declaration.validation}];
  const proposal={editProposalVersion:'0.1',contextSha256:context.sha256,patch:{patchVersion:'0.1',baseSpecSha256:context.baseSpecSha256,reason:'Deterministic interaction acceptance fixture; no model invocation',operations},decisions:operations.map((_,operationIndex)=>({operationIndex,basis:{kind:'request-interpretation',quote:text,start:0,end:text.length}})),unresolved:[]};const checked=await checkPanelEditProposal(context,proposal);assert.equal(checked.status,'READY_TO_APPLY');await a.save('fixture-edit-proposal.json',proposal);await a.page.locator('#edit-proposal-file').setInputFiles({name:'fixture-edit.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(proposal))});await a.idle();const edited=await a.panel();assert.equal(field(edited,find(edited,'角色名')).initial,'测试名');assert.equal(field(edited,find(edited,'角色宣言')).maxLength,40);assert.deepEqual(await a.state(),before);a.pass('fixture-edit-preserves-both-page-trial-inputs');await a.undo();assert.deepEqual((await a.panel()).spec,b.spec);assert.deepEqual(await a.state(),before);a.pass('fixture-edit-undo-restores-full-spec-and-inputs');await a.exportCheck();
 },
 COM03:async a=>{
  const b=await actualGenerate(a);assert.deepEqual(flat(b).map(r=>r.kind),['text','progress','progress','switch','button','button']);assert.equal(flat(b)[0].text,'正在加载资源');const [loading,downloaded]=flat(b).filter(r=>r.kind==='progress');assert.match(loading.label,/^加载进度(?:条)?$/u);assert.match(downloaded.label,/^已下载(?:进度条)?$/u);const sound=find(b,'提示音'),cancel=button(b,'取消加载');for(const [r,max,initial,mode,digits]of [[loading,100,25,'percent',0],[downloaded,250,50,'value',1]]){assert.deepEqual([field(b,r).max,field(b,r).initial,r.format.mode,r.format.fractionDigits],[max,initial,mode,digits]);}assert.equal(field(b,sound).initial,true);assert.equal(cancel.action.kind,'emit');const reset=button(b,'重新开始');assert.deepEqual([...reset.action.fields].sort(),[loading.bind,downloaded.bind].sort());a.pass('loading-facts-determinate-bars-text-and-actions');
  const count=(await a.events()).length;await a.page.evaluate(({a,b})=>{window.panelHost.setProgress(a,63.75);window.panelHost.setProgress(b,159.375);},{a:loading.bind,b:downloaded.bind});assert.equal((await a.state())[loading.bind],63.75);assert.equal((await a.state())[downloaded.bind],159.375);assert.equal((await a.events()).length,count);let nodes=(await a.inspect()).nodes;const texts=nodes.flatMap(n=>n.renderedTextBounds??[]).map(t=>t.text);assert(texts.includes('64%'));assert(texts.includes('159.4'));a.pass('host-updates-render-values-without-player-events');
  const node=nodes.find(n=>n.id===controlId(b.spec.id,loading.id)),canvas=a.page.locator('#canvas-host canvas');await canvas.scrollIntoViewIfNeeded();const rect=await canvas.boundingBox(),x=rect.x+(node.bounds.x+node.bounds.width/2)*rect.width/b.spec.canvas.width,y=rect.y+(node.bounds.y+node.bounds.height/2)*rect.height/b.spec.canvas.height;const before=await a.state();await a.page.mouse.move(x,y);await a.page.mouse.down();await a.page.mouse.move(x+40,y);await a.page.mouse.up();assert.deepEqual(await a.state(),before);await canvas.focus();for(let i=0;i<8;i++){await a.page.keyboard.press('Tab');assert.notEqual(await canvas.getAttribute('data-focused-component'),node.id);}a.pass('progress-readonly-no-drag-or-keyboard-focus');
  const invalid=await a.page.evaluate(id=>{const result=[];for(const value of [-1,101,Infinity,'20']){try{window.panelHost.setProgress(id,value);result.push(false);}catch{result.push(true);}}return result;},loading.bind);assert(invalid.every(Boolean));assert.deepEqual(await a.state(),before);a.pass('invalid-host-progress-rejected-atomically');await a.click(b,sound);const preCancel=await a.state();await a.click(b,cancel);assert.deepEqual(await a.state(),preCancel);a.pass('cancel-event-keeps-host-progress');await scopedReset(a,b,'重新开始',[loading.label,downloaded.label]);assert.equal((await a.state())[sound.bind],false);await a.exportCheck();
 }
};

return cases;
}
