import {deflateSync} from 'node:zlib';
import { appearanceDocumentSha256 } from '../../src/appearance-binding.ts';
import { applyAppearanceBinding } from '../../src/appearance-apply.ts';
import { createBundle, validateBundle } from '../../src/bundle.ts';
import { importDecompositionZip } from '../../src/decomposition-import.ts';
import { fixtureLayeredZip } from './decomposition-fixture.ts';
import { scrollHitArea } from '../../src/scroll-hit-area.ts';
const style = { backgroundColor:'#151515',borderColor:'#555555',borderWidth:0,cornerRadius:0,textColor:'#FFFFFF',fontFamily:'sans-serif',fontSize:16,fontWeight:'normal',opacity:1 };
export async function sliceFixture(scale=1) {
 const document:any={schemaVersion:'0.2',id:'external-track',canvas:{width:300*scale,height:250*scale},root:{id:'root',type:'Container',layout:{x:0,y:0,width:300*scale,height:250*scale},props:{style},children:[{id:'parent',type:'Container',layout:{x:20*scale,y:30*scale,width:250*scale,height:200*scale},props:{style},children:[{id:'scroll',type:'ScrollView',layout:{x:10*scale,y:10*scale,width:100*scale,height:120*scale},props:{style,scrollX:0,scrollY:0,contentWidth:100*scale,contentHeight:240*scale},children:[]}]}]}};
 const f=await fixtureLayeredZip([300,250],[{id:'scene',role:'background',left:0,top:0,width:300,height:250},{id:'viewport',role:'important_component',left:30,top:40,width:100,height:120},{id:'track',role:'important_component',left:140,top:45,width:14,height:110},{id:'thumb',role:'important_component',left:142,top:45,width:10,height:20,bytes:bandPng()}]);
 const imported=await importDecompositionZip(f.zip);
 const target=await createBundle(document,[],{kind:'programmatic-fixture',description:'Nested viewport with explicitly external vertical scrollbar; local fixture only.'});
 const binding:any={kind:'ui-appearance-binding',version:'0.2',documentSha256:await appearanceDocumentSha256(document),deliveryDigest:imported.deliveryDigest,sceneSha256:imported.sceneSha256,archiveSha256:imported.archiveSha256,registration:{sourceCanvas:{width:300,height:250},targetCanvas:document.canvas,transform:{scale,offset:{x:0,y:0}}},bindings:[{componentId:'scroll',componentType:'ScrollView',parts:[{role:'viewport',layerId:'viewport'},{role:'scrollbar-track',layerId:'track'},{role:'scrollbar-thumb',layerId:'thumb'}],states:{scrollView:{thumbPositions:{coordinateSpace:'target-component-local',anchor:'top-left',min:{x:112*scale,y:5*scale},max:{x:112*scale,y:95*scale}}}}}]};
 binding.bindings[0].states.scrollView.scrollbarInsets={version:'1.0',top:20*scale,bottom:20*scale};binding.bindings[0].states.scrollView.scrollbarThumbSlices={version:'1.0',coordinateSpace:'thumb-source-pixels',top:4,bottom:5};return {target,imported,binding,zip:f.zip};
}

function bandPng(){const crc=(b:Uint8Array)=>{let c=0xffffffff;for(const v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;};const chunk=(name:string,data:Uint8Array)=>{const t=Buffer.concat([Buffer.from(name),data]);const b=Buffer.alloc(t.length+8);b.writeUInt32BE(data.length);b.set(t,4);b.writeUInt32BE(crc(t),b.length-4);return b;};const header=Buffer.alloc(13);header.writeUInt32BE(10);header.writeUInt32BE(20,4);header[8]=8;header[9]=6;const raw=Buffer.alloc(41*20);for(let y=0;y<20;y++)for(let x=0;x<10;x++)raw.set(y<4?[255,0,0,255]:y>=15?[0,0,255,255]:[0,255,0,255],y*41+1+x*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
import{zip as packZip,referenceSha256}from'../../src/reference-persistence.ts';
export async function sliceHandoff(){const f=await sliceFixture();const enc=(v:unknown)=>new TextEncoder().encode(JSON.stringify(v));const state={kind:'ui-reference-state',schemaVersion:'1.0',components:[{componentId:'scroll',componentType:'ScrollView',fields:{scrollX:{status:'unknown',reason:'Fixture explicitly retains unknown reference offset'},scrollY:{status:'unknown',reason:'Fixture explicitly retains unknown reference offset'}}}]};const scope={kind:'ui-acceptance-scope',schemaVersion:'1.0',referenceState:'reference/reference-state.json',human_visual_acceptance:false,derivedTestStates:[],components:['root','parent','scroll'].map(componentId=>({componentId,mode:'compare',reason:'Deterministic slice fixture'}))};const e=new Map<string,Uint8Array>([['component.ui-bundle.json',enc(f.target)],['appearance-binding.json',enc(f.binding)],['decomposition/fixture.zip',f.zip],['reference/original.png',f.imported.preview.bytes],['reference/reference-state.json',enc(state)],['acceptance-scope.json',enc(scope)]]);const entry=async(path:string)=>({path,sha256:await referenceSha256(e.get(path)!)});e.set('handoff.json',enc({kind:'ai_ui_component_handoff_v2',schemaVersion:'2.0',status:'contracts_packaged_unreviewed_draft',delivery_policy:'unreviewed_draft',human_visual_acceptance:false,component_bundle:await entry('component.ui-bundle.json'),appearance_binding:await entry('appearance-binding.json'),decomposition:await entry('decomposition/fixture.zip'),reference:{original:{...await entry('reference/original.png'),width:300,height:250},state:await entry('reference/reference-state.json'),scope:await entry('acceptance-scope.json'),mapping:{coordinateSpace:'raw-image-pixel-edges-to-runtime-canvas',sourceSize:[300,250],targetSize:[300,250],crop:[0,0,300,250],rotationDegrees:0,flipX:false,flipY:false,scale:[1,1],offset:[0,0]},derivatives:[]}}));return packZip(e);}
