import type { UiDocument } from '../../src/tree-contract.ts';
export function stateTemplateFixture(): UiDocument {
 const style={backgroundColor:'#FFFFFF',borderColor:'#000000',borderWidth:0,cornerRadius:0,textColor:'#000000',fontFamily:'sans-serif',fontSize:14,fontWeight:'normal' as const,opacity:1};
 return {schemaVersion:'0.2',id:'state-template-fixture',canvas:{width:240,height:180},root:{id:'root',type:'Container',layout:{x:0,y:0,width:240,height:180},props:{style},children:[
  {id:'list',type:'List',layout:{x:0,y:60,width:200,height:120},props:{selectedId:'a',items:[{id:'a',label:'A'},{id:'b',label:'B'},{id:'c',label:'C'}],itemTemplate:'text-row',itemHeight:40,enabled:true,style,appearance:{templateSizing:'independent',sourceCanvas:{width:200,height:120},backgroundPolicy:{version:'1.0',mode:'parent'},rowImage:'row.svg',rowCanvas:{width:200,height:40},selectedRowImage:'selected.svg',selectedRowCanvas:{width:180,height:38},selectedTextColor:'#FFFFFF',selectedIndicator:{image:'marker.svg',canvas:{width:10,height:10},layout:{x:170,y:15,width:10,height:10}},labelLayout:{x:10,y:5,width:120,height:30},hitArea:{x:0,y:0,width:200,height:40}}},children:[]},
  {id:'tabs',type:'Tabs',layout:{x:0,y:0,width:240,height:60},props:{activeId:'tab-a',tabs:[{id:'tab-a',label:'A',contentId:'a-page'},{id:'tab-b',label:'B',contentId:'b-page'}],enabled:true,drawBackground:false,style,appearance:{templateSizing:'independent',sourceCanvas:{width:240,height:60},tabImage:'tab.svg',tabCanvas:{width:120,height:40},activeTabImage:'active-tab.svg',activeTabCanvas:{width:116,height:38},headerHeight:40,labelLayout:{x:10,y:5,width:100,height:30},hitArea:{x:0,y:0,width:120,height:40}}},children:['a','b'].map(id=>({id:id+'-page',type:'Container' as const,layout:{x:0,y:40,width:240,height:20},props:{style},children:[]}))}
 ]}};
}
export function stateTemplateResources(){const svg=(width:number,height:number,color:string)=>new TextEncoder().encode(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="${color}"/></svg>`);return [['row.svg',200,40,'#FFFFFF'],['selected.svg',180,38,'#008080'],['marker.svg',10,10,'#FFFF00'],['tab.svg',120,40,'#FFFFFF'],['active-tab.svg',116,38,'#008080']].map(([path,w,h,color])=>({path:path as string,mime:'image/svg+xml',bytes:svg(w as number,h as number,color as string)}));}
