import test from 'node:test';import assert from 'node:assert/strict';
import {listTextDocument,listTextHandoffFixture,skillItems} from './helpers/list-text-fixture.ts';
import {validateDocument} from '../src/tree-contract.ts';import {formatValueText} from '../src/value-text-bindings.ts';
import {importComponentHandoffWithReview} from '../src/component-handoff.ts';import {exportReferenceHandoff} from '../src/reference-persistence.ts';import {componentHandoffEntries} from '../src/decomposition-import.ts';import {validateBundle} from '../src/bundle.ts';import {bindHandoffValueText} from '../src/value-text-handoff.ts';
test('1.1 selectedId maps all six explicit case-sensitive labels, null is explicit, no guessed fallback',()=>{const d=listTextDocument();validateDocument(d);const b=d.valueTextBindings!.bindings[0];for(const[id,text]of skillItems)assert.equal(formatValueText(b,{selectedId:id}),'Selected: '+text);assert.equal(formatValueText(b,{selectedId:null}),'Selected: (none)');assert.throws(()=>formatValueText(b,{selectedId:'missing'}),/ITEM_REFERENCE/);assert.throws(()=>formatValueText(b,{}),/ITEM_REFERENCE/);assert.equal(formatValueText(d.valueTextBindings!.bindings[2],{value:2480,max:5000}),'2,480 / 5,000');});
const cases:Record<string,(d:any)=>void>={version:d=>d.valueTextBindings.version='1.2',oldVersionList:d=>d.valueTextBindings.version='1.0',source:d=>d.valueTextBindings.bindings[0].sourceId='missing',sourcePath:d=>d.valueTextBindings.bindings[0].sourceId='../skill-list',targetPath:d=>d.valueTextBindings.bindings[0].targetId='file:///label',cycle:d=>d.valueTextBindings.bindings[0].sourceId='selected-name',targetType:d=>d.valueTextBindings.bindings[0].targetId='power',conflict:d=>d.valueTextBindings.bindings.push(d.valueTextBindings.bindings[0]),mixedConflict:d=>d.valueTextBindings.bindings[1].targetId='selected-name',missingMap:d=>d.valueTextBindings.bindings[0].parts[1].items.pop(),duplicateItem:d=>d.valueTextBindings.bindings[0].parts[1].items[0].itemId='tidal',invalidItem:d=>d.valueTextBindings.bindings[0].parts[1].items[0].itemId='unknown',itemPath:d=>d.valueTextBindings.bindings[0].parts[1].items[0].itemId='../ember',missingEmpty:d=>delete d.valueTextBindings.bindings[0].parts[1].emptyText,emptyType:d=>d.valueTextBindings.bindings[0].parts[1].emptyText=null,textControl:d=>d.valueTextBindings.bindings[0].parts[1].items[0].text='bad\ntext',longText:d=>d.valueTextBindings.bindings[0].parts[1].items[0].text='a'.repeat(129),script:d=>d.valueTextBindings.bindings[0].parts[1].script='alert(1)',pathField:d=>d.valueTextBindings.bindings[0].parts[1].path='items[selectedId]',wrongListField:d=>d.valueTextBindings.bindings[0].parts[1].field='label',numericList:d=>d.valueTextBindings.bindings[0].parts[1]={field:'value',fractionDigits:0,grouping:'none'},selectedNumeric:d=>d.valueTextBindings.bindings[1].parts=d.valueTextBindings.bindings[0].parts,literalOnly:d=>d.valueTextBindings.bindings[0].parts=['no source'],editedItems:d=>d.root.children[0].props.items.push({id:'new',label:'New'})};
for(const[name,mutate]of Object.entries(cases))test('List text rejects '+name,()=>{const d=listTextDocument();mutate(d);assert.throws(()=>validateDocument(d));});
test('empty List has explicit empty map; mapping order independent; scripts are literal text only',()=>{const d:any=listTextDocument();d.root.children[0].props.selectedId=null;d.root.children[0].props.items=[];d.valueTextBindings.bindings[0].parts[1].items=[];validateDocument(d);assert.equal(formatValueText(d.valueTextBindings.bindings[0],{selectedId:null}),'Selected: (none)');const other:any=listTextDocument();other.valueTextBindings.bindings[0].parts[1].items.reverse();other.valueTextBindings.bindings[0].parts[1].items.find(i=>i.itemId==='ember').text='<script>literal</script>';validateDocument(other);assert.equal(formatValueText(other.valueTextBindings.bindings[0],{selectedId:'ember'}),'Selected: <script>literal</script>');});
test('List text v2 package save/reopen/export preserves binding and reference bytes',async()=>{const f=await listTextHandoffFixture();const imported=await importComponentHandoffWithReview(f.zip);const saved:any=JSON.parse(JSON.stringify(imported.bundle));saved.document.root.children[0].props.selectedId='iron';const validated=await validateBundle(saved);const out=await exportReferenceHandoff(validated);const again=await importComponentHandoffWithReview(out);assert.deepEqual(again.bundle.document,saved.document);const a=await componentHandoffEntries(f.zip),b=await componentHandoffEntries(out);for(const[n,bytes]of a)if(n!=='handoff.json')assert.deepEqual(b.get(n),bytes,n);const rebound=await bindHandoffValueText(f.zip,f.document.valueTextBindings);assert.deepEqual((await importComponentHandoffWithReview(rebound)).bundle.document.valueTextBindings,f.document.valueTextBindings);});
