import test from 'node:test';import assert from 'node:assert/strict';
import {listBackgroundFixture} from './helpers/list-background-fixture.ts';
import {compileComponentHandoff} from '../src/component-handoff.ts';
import {componentHandoffEntries} from '../src/decomposition-import.ts';
import {zip,referenceSha256} from '../src/reference-persistence.ts';
import {validateDocument,walkNodes} from '../src/tree-contract.ts';
async function mutate(change:(v:any)=>void){const f=await listBackgroundFixture('parent');const e=await componentHandoffEntries(f.zip);const b=JSON.parse(new TextDecoder().decode(e.get('appearance-binding.json')));change(b);e.set('appearance-binding.json',new TextEncoder().encode(JSON.stringify(b)));const m=JSON.parse(new TextDecoder().decode(e.get('handoff.json')));m.appearance_binding.sha256=await referenceSha256(e.get('appearance-binding.json')!);e.set('handoff.json',new TextEncoder().encode(JSON.stringify(m)));return zip(e);}
for(const mode of [undefined,'own','parent'] as const)test('List background official import '+String(mode),async()=>{const c=await compileComponentHandoff((await listBackgroundFixture(mode)).zip);const l=walkNodes(c.bundle.document as any).find(n=>n.type==='List')!;if(l.type!=='List')throw Error();assert.equal(l.props.appearance?.backgroundPolicy?.mode,mode);assert.equal(!!l.props.appearance?.backgroundImage,mode!=='parent');assert.deepEqual(l.props.appearance?.sourceCanvas,{width:400,height:300});assert.equal(l.props.itemContents?.items.length,6);});
for(const [name,change] of Object.entries({version:(b:any)=>b.bindings[0].states.list.backgroundPolicy.version='2',mode:(b:any)=>b.bindings[0].states.list.backgroundPolicy.mode='none',ownMissing:(b:any)=>b.bindings[0].states.list.backgroundPolicy.mode='own',forbidden:(b:any)=>b.bindings[0].parts.push({role:'background',layerId:'scene-background'}),missing:(b:any)=>delete b.bindings[0].states.list.backgroundPolicy,reference:(b:any)=>b.bindings[0].parts[0].layerId='missing',geometry:(b:any)=>b.registration.transform.offset.y=1,extra:(b:any)=>b.bindings[0].states.list.backgroundPolicy.extra=true}))test('List background rejects '+name,async()=>{await assert.rejects(async()=>compileComponentHandoff(await mutate(change)));});
test('runtime appearance rejects background conflicts and invalid policy',async()=>{const c=await compileComponentHandoff((await listBackgroundFixture('parent')).zip);const d=structuredClone(c.bundle.document);const l=walkNodes(d as any).find(n=>n.type==='List')!;if(l.type!=='List')throw Error();l.props.appearance!.backgroundImage=l.props.appearance!.rowImage;assert.throws(()=>validateDocument(d));delete l.props.appearance!.backgroundImage;(l.props.appearance!.backgroundPolicy as any).version='2';assert.throws(()=>validateDocument(d));delete l.props.appearance!.backgroundPolicy;assert.throws(()=>validateDocument(d));});
