/** Static markup; all untrusted JSON is escaped out of HTML/script syntax. */
export function renderWorkbenchHtml(seed) {
  const embedded = JSON.stringify(seed).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>Panel Studio · UI 面板工作台</title>
<style>
:root{color-scheme:dark;--bg:#101b22;--surface:#192830;--raised:#22363e;--border:#48616a;--text:#f0f7f5;--muted:#afc5c7;--accent:#6ad8bd;--on-accent:#102c29;--error:#ffb5a9;--radius:12px;font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
#edit-changes-list,#edit-check-list{padding-left:20px;overflow-wrap:anywhere}#edit-changes-list li,#edit-check-list li{margin:6px 0}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text)}button,input,textarea,select{font:inherit}button,.file-button,summary{touch-action:manipulation}button,.file-button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--raised);color:var(--text);padding:10px 14px;cursor:pointer;transition:background 160ms,border-color 160ms}button:hover,.file-button:hover{background:#304950;border-color:var(--accent)}button:active,.file-button:active{background:#39545b}button.primary{background:var(--accent);color:var(--on-accent);border-color:var(--accent);font-weight:650}button.primary:hover{background:#85e3cc}button:disabled{opacity:.4;cursor:default}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,summary:focus-visible,.file-button:focus-within{outline:3px solid var(--accent);outline-offset:3px}
input,textarea,select{max-width:100%;border:1px solid var(--border);border-radius:8px;color:var(--text);background:#101f26;padding:10px 12px}textarea{width:100%;resize:vertical;min-height:110px;line-height:1.65}textarea::placeholder,input::placeholder{color:#92aeb4}input[type=checkbox]{width:18px;height:18px;accent-color:var(--accent)}label{display:block;margin:12px 0 8px;font-weight:550}h1,h2,h3,p{margin:0}h1{font-size:21px;font-weight:650;letter-spacing:-.4px}h2{font-size:17px}h3{font-size:14px;color:var(--muted)}.hint{font-size:13px;color:var(--muted);line-height:1.7;overflow-wrap:anywhere}.hint:empty{display:none}
header{padding:18px 24px;display:flex;align-items:center;gap:24px;border-bottom:1px solid #30434b}.brand{margin-right:auto}#status{font-size:13px;color:var(--accent);overflow-wrap:anywhere}#status:empty{display:none}.workspace{max-width:1600px;margin:0 auto;display:grid;grid-template-columns:minmax(280px,360px) minmax(0,1fr);gap:24px;padding:24px;align-items:start}.column{min-width:0}.card{background:var(--surface);border:1px solid #3b525b;border-radius:var(--radius);padding:20px;margin-bottom:16px}.main-label{margin:0 0 12px;font-size:16px}.card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.actions button{flex:1}.full{width:100%}.error{color:var(--error);font-size:13px;margin-top:12px;white-space:pre-wrap;overflow-wrap:anywhere}.error:empty{display:none}.feedback{margin-top:12px}.feedback:empty{display:none}summary{cursor:pointer;color:var(--muted);font-size:13px;padding:12px 0}details{margin-top:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.7 ui-monospace,Consolas,monospace;color:var(--muted);max-height:230px;overflow:auto;margin:8px 0}.code-input{font:12px/1.6 ui-monospace,Consolas,monospace}.file-button{display:inline-flex;align-items:center;margin:0;font-weight:400}.file-button input{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
.preview-toolbar{display:flex;gap:16px;align-items:center;justify-content:space-between;padding-bottom:16px}.preview-toolbar p{font-size:13px;color:var(--muted);margin-top:4px;overflow-wrap:anywhere}.preview-surface{background:#132a31;border:1px solid #3b525b;border-radius:var(--radius);min-height:520px;display:grid;place-items:center;overflow:hidden;position:relative}#canvas-host{width:100%;min-width:0}#canvas-host:empty{display:none}#canvas-host canvas{display:block;width:100%;height:auto;outline-offset:-3px}.empty{padding:48px 24px;text-align:center;max-width:420px}.empty strong{display:block;font-size:20px;font-weight:550;margin-bottom:12px}.empty p{color:var(--muted);font-size:14px}.empty .outline{width:144px;height:104px;border:1px solid #536e76;border-radius:14px;margin:0 auto 24px;padding:20px}.empty .outline i{display:block;border:1px solid #536e76;border-radius:4px;height:12px;margin-bottom:8px}.preview-footer{margin-top:12px;font-size:12px;color:var(--muted);display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}#preview-note{margin:0 0 12px;font-size:13px;color:var(--accent)}#preview-note:empty{display:none}
.panel-menu{position:relative;flex:none;margin:0}.panel-menu>summary{list-style:none;min-height:44px;border:1px solid var(--border);border-radius:8px;padding:10px 14px;color:var(--text);background:var(--raised)}.panel-menu>summary::-webkit-details-marker{display:none}.panel-menu>summary::after{content:' ▾';color:var(--muted)}.panel-menu[open]>summary{border-color:var(--accent)}.menu-items{position:absolute;z-index:10;right:0;top:calc(100% + 8px);width:220px;padding:8px;background:var(--surface);border:1px solid var(--border);border-radius:10px;box-shadow:0 8px 24px #0005;display:flex;flex-direction:column;gap:8px}.menu-items button,.menu-items .file-button{width:100%;text-align:left}.menu-items hr{width:100%;border:0;border-top:1px solid #3b525b;margin:0}
#questions{padding:0;list-style:none;font-size:13px;color:var(--muted)}#questions textarea{min-height:72px}#questions li{margin-bottom:12px}#clarification-form{border-top:1px solid var(--border);padding-top:16px;margin-top:16px}#edit-questions:empty{display:none}#edit-questions{padding-left:20px;margin:12px 0;font-size:13px;color:var(--muted)}#edit-hint{margin-top:12px}.advanced-only{display:none}.advanced-mode .advanced-only{display:block}.advanced-area{grid-column:1/-1}.advanced-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.badge{font-size:12px;border:1px solid var(--border);border-radius:30px;padding:4px 10px;color:var(--muted)}.steps{display:flex;gap:24px;list-style:none;padding:0;margin:0 0 16px;color:var(--muted)}.steps li{display:flex;gap:8px;align-items:center;font-size:13px}.steps li.current{color:var(--accent)}.candidates{display:grid;grid-template-columns:1fr 1fr;gap:8px;max-height:280px;overflow:auto;padding:2px}.candidate{border:1px solid var(--border);border-radius:8px;padding:8px;min-width:0;background:#203b40}.candidate img{width:32px;height:32px;object-fit:contain;display:block;margin-bottom:6px}.candidate p{font-size:12px;overflow-wrap:anywhere}.candidate small{display:block;color:var(--muted);font-size:11px}#live-state{display:grid;grid-template-columns:1fr auto;font-size:13px;gap:8px;margin:0}#live-state dt{color:var(--muted)}#live-state dd{margin:0;text-align:right}.checkline{display:flex;gap:8px;align-items:center;font-size:14px}.initial-note{font-size:12px;color:var(--muted);margin-top:8px}#editor-form fieldset{padding:0;border:0;margin:0;min-width:0}#editor-form input:not([type=checkbox]),#editor-form select{width:100%}#history-list{padding-left:20px;font-size:13px;color:var(--muted)}.divider{height:1px;background:#3b525b;margin:16px 0}[hidden]{display:none!important}.busy{cursor:progress}.busy .preview-surface{opacity:.86}.skip-link{position:absolute;left:16px;top:8px;transform:translateY(-150%);z-index:20;padding:8px;background:var(--accent);color:var(--on-accent)}.skip-link:focus{transform:none}
@media(max-width:1024px){.workspace{grid-template-columns:300px minmax(0,1fr);padding:16px;gap:16px}.preview-surface{min-height:400px}.advanced-grid{grid-template-columns:1fr 1fr}}@media(max-width:760px){:root{font-size:16px}header{padding:16px;gap:16px;flex-wrap:wrap}.workspace{padding:16px;display:flex;flex-direction:column;gap:8px}.column,.advanced-area{width:100%}.card{padding:16px}.preview-surface{min-height:280px}.preview-toolbar{padding-top:8px}.advanced-grid{display:block}.menu-items{width:min(220px,calc(100vw - 32px))}.preview-footer{margin-bottom:16px}#status{font-size:13px}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
#request-help{margin-bottom:8px}.suggested-answers{display:flex;flex-direction:column;gap:8px;margin:8px 0}.suggested-answers button{text-align:left;white-space:normal;overflow-wrap:anywhere;font-size:13px}.suggested-answers button[aria-pressed=true]{border-color:var(--accent);background:#23463f;color:var(--text)}#questions li,#edit-questions li{margin-bottom:16px}#edit-questions{padding:0;list-style:none}#edit-questions textarea{min-height:72px}#edit-clarification-form{border-top:1px solid var(--border);padding-top:16px;margin-top:16px}#requirement-summary{font-size:13px;padding:12px 16px;border:1px solid #3b525b;border-radius:8px;background:var(--surface);margin-bottom:16px;overflow-wrap:anywhere}#summary-details{padding-left:20px;color:var(--muted);margin:8px 0}#summary-details li{margin-bottom:8px}#requirement-summary summary{padding:8px 0 0}
.advanced-mode .preview-toolbar{flex-wrap:wrap}.advanced-mode .panel-menu{width:100%}.advanced-mode .menu-items{position:static;width:100%;flex-direction:row;flex-wrap:wrap;box-shadow:none;margin-top:8px}.advanced-mode .menu-items button,.advanced-mode .menu-items .file-button{width:auto;flex:1 1 160px}.advanced-mode .menu-items hr{display:none}
.preview-toolbar{flex-wrap:wrap}.preview-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.preview-actions>button{white-space:nowrap}.advanced-mode .preview-actions{width:100%}
.save-status{font-size:12px;color:var(--muted);margin-top:8px}.save-status[data-error=true]{color:var(--error)}dialog{color:var(--text);background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:24px;width:min(560px,calc(100vw - 32px));max-height:85vh;overflow:auto}dialog::backdrop{background:#0008}.saved-versions{list-style:none;padding:0;margin:16px 0}.saved-versions li{border-top:1px solid var(--border);padding:12px 0;display:flex;align-items:center;gap:12px}.saved-versions li>div{flex:1;min-width:0;overflow-wrap:anywhere}.saved-versions button{flex:none}.dialog-head{display:flex;align-items:center;justify-content:space-between;gap:12px}
.selection-layer{position:absolute;z-index:3;background:#101b221a}.selection-target{position:absolute;padding:0;min-height:0;min-width:0;border:2px dashed #0d7767;border-radius:8px;background:#6ad8bd0d;cursor:crosshair}.selection-target:hover,.selection-target:focus-visible{background:#6ad8bd33;border:3px solid #0d7767;outline:2px solid #fff;outline-offset:-5px}.selection-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-bottom:12px}.edit-target{border-left:3px solid var(--accent);padding:8px 12px;margin:0 0 12px;background:var(--raised);font-size:13px;overflow-wrap:anywhere}.edit-target .hint{margin-top:4px}#selection-help{margin:0 0 12px;color:var(--accent)}
</style></head><body>
<a class="skip-link" href="#request-text">跳到需求描述</a>
<header><div class="brand"><h1>Panel Studio</h1></div><p id="status" role="status" aria-live="polite">正在初始化…</p></header>
<main class="workspace">
<div class="column request-column">
<section class="card" aria-label="生成面板">
<label class="main-label" id="request-heading" for="request-text">需求描述</label><p id="request-help" class="hint">说说玩家要做什么，不必写控件名。</p><textarea id="request-text" rows="7" placeholder="例如：做一个声音设置，可以调音量、静音，还能恢复默认。" aria-describedby="request-help request-error bridge-notice" data-mutation></textarea>
<div class="actions"><button id="generate-plan" class="primary" data-mutation disabled>生成面板</button><button id="cancel-plan" hidden disabled>取消生成</button></div>
<details id="requirement-examples"><summary>不知道怎么说？看几个例子</summary><p class="hint">选用例子会替换当前需求，可继续修改；不会自动生成。</p><div id="example-choices" class="suggested-answers"></div></details>
<p id="bridge-notice" class="hint feedback" hidden></p><p id="request-error" class="error" role="alert"></p><p id="proposal-error" class="error" role="alert"></p>
<form id="clarification-form" hidden><h2>再确认一下</h2><p class="hint">推荐回答供你选择，也可以自己填写。选择后不会自动生成。</p><ul id="questions"></ul><p class="hint">采用全部回答后，再点击「生成面板」。</p><div class="actions"><button id="clarify" type="submit" data-mutation disabled>采用回答</button></div><p id="clarification-error" class="error" role="alert"></p></form>
</section>
<section class="card" aria-label="修改面板">
<label class="main-label" id="edit-heading" for="edit-request-text">修改要求</label><div class="selection-tools"><button id="select-edit-target" type="button" aria-pressed="false" aria-controls="canvas-host" disabled>选择修改对象</button><button id="clear-edit-target" type="button" hidden>取消选择</button></div><div id="edit-target" class="edit-target" role="status" aria-live="polite" hidden><strong id="edit-target-name"></strong><p class="hint">“这个”指选中控件。要修改整页或其他控件，请先取消选择。</p></div><textarea id="edit-request-text" rows="4" placeholder="例如：增加音效音量；把界面改成深色蓝色，其他保持不变。" aria-describedby="edit-target edit-hint edit-plan-error" data-mutation disabled></textarea>
<div class="actions"><button id="generate-edit" class="primary" data-mutation disabled>修改面板</button><button id="cancel-edit" hidden disabled>取消修改</button></div>
<p id="edit-rounds" class="hint feedback" role="status" aria-live="polite"></p><details id="edit-changes" hidden><summary id="edit-changes-heading">上次实际变化</summary><p class="hint" id="edit-check-summary"></p><ul id="edit-check-list" class="hint"></ul><ul id="edit-changes-list" class="hint"></ul></details><p class="hint" id="edit-hint">生成或打开面板后即可修改。</p><p id="edit-plan-status" class="hint feedback" role="status" aria-live="polite"></p><p id="edit-plan-error" class="error" role="alert"></p><form id="edit-clarification-form" hidden><h2>再确认一下</h2><p class="hint">选择回答或自己填写，采用后再点击「修改面板」。</p><ul id="edit-questions"></ul><button id="clarify-edit" type="submit" data-mutation disabled>采用回答</button><p id="edit-clarification-error" class="error" role="alert"></p></form><p id="edit-error" class="error" role="alert"></p>
</section></div>
<section class="column preview-column" aria-labelledby="preview-heading">
<div class="preview-toolbar"><div><h2 id="preview-heading">交互预览</h2><p id="panel-name">尚未生成面板</p></div><div class="preview-actions"><button id="download-delivery" type="button" disabled>下载交付包</button><details class="panel-menu" id="panel-menu"><summary>面板操作</summary><div class="menu-items"><button id="open-saved-history" type="button" disabled>历史版本与本机存档</button><button id="undo" type="button" data-mutation disabled>撤销上次修改</button><button id="download-panel" disabled>导出当前面板</button><button id="download-unity" aria-describedby="unity-export-help" disabled>下载 Unity 工具包</button><button id="download-shared-sdk" type="button" disabled>下载共享接入 SDK</button><label class="file-button">打开面板<input id="panel-file" type="file" accept="application/json,.json" data-mutation disabled></label><button id="example" data-mutation disabled>载入完整示例</button><hr><button id="advanced-tools" type="button" aria-controls="advanced-area" aria-expanded="false">高级工具</button></div></details></div></div>
<p id="save-status" class="save-status" role="status" aria-live="polite"></p><p id="preview-note"></p><div id="requirement-summary" hidden><p id="summary-overview"></p><details><summary>默认值与按钮行为</summary><p class="hint">下面是生成结果的约定。试玩值可能不同；默认值在恢复默认时生效。</p><ul id="summary-details"></ul></details></div><p id="selection-help" class="hint" role="status" hidden>点击框内控件选择；也可用 Tab 和 Enter。Esc 返回试玩。要选屏幕外的控件，请先返回试玩并滚动。</p><div class="preview-surface"><div id="empty-preview" class="empty"><div class="outline" aria-hidden="true"><i></i><i></i><i></i></div><strong>面板将在这里显示</strong><p>填写左侧需求，点击「生成面板」。</p></div><div id="canvas-host"></div></div><p id="preview-error" class="error" role="alert"></p><div class="preview-footer"><span id="panel-dimensions">支持鼠标和键盘</span><span>仅预览，未连接游戏设置</span></div><p id="unity-export-status" class="hint feedback" role="status" aria-live="polite"></p>
</section>
<section class="advanced-only advanced-area" id="advanced-area" aria-label="高级工具">
<div class="card-head"><h2>高级工具</h2><span class="badge" id="library-badge">正在检查资源</span></div>
<ol class="steps" aria-label="工作流程"><li id="step-request" class="current">准备需求</li><li id="step-proposal">接收方案</li><li id="step-preview">预览与修改</li></ol>
<div class="advanced-grid"><section class="card"><h3>规划与资源</h3><p id="model-status" class="hint"></p><details id="model-help" hidden><summary>本地模型入口</summary><p class="hint">用本地启动命令打开工作台后，可直接生成和修改。每次点击只调用一次模型，失败不自动重试。</p></details><details><summary>需求标识与资源风格</summary><label for="request-id">需求标识</label><input id="request-id" value="my-panel" class="full" data-mutation><label for="asset-style">资源风格</label><select id="asset-style" class="full" data-mutation><option value="">全部风格</option></select></details><div class="actions"><button id="prepare" data-mutation disabled>仅准备规划上下文</button></div><div id="context-ready" hidden><div class="actions"><button id="download-context" disabled>导出规划文件</button></div><details><summary id="candidate-summary">资源候选</summary><div id="candidates" class="candidates"></div></details></div></section>
<section class="card" aria-labelledby="proposal-heading"><h3 id="proposal-heading">接收 Agent 方案</h3><label class="file-button" style="margin-top:12px">导入方案文件<input id="proposal-file" type="file" accept="application/json,.json" data-mutation disabled></label><details id="proposal-details"><summary>或粘贴方案 JSON</summary><label for="proposal-json">完整方案</label><textarea id="proposal-json" class="code-input" rows="5" data-mutation></textarea></details><div class="actions"><button id="accept-proposal" data-mutation disabled>校验并生成预览</button></div><div class="divider"></div><h3>接收修改方案</h3><div class="actions"><button id="prepare-edit-context" data-mutation disabled>仅准备修改上下文</button></div><div class="actions"><button id="download-edit-context" disabled>导出修改规划</button><label class="file-button">导入修改方案<input id="edit-proposal-file" type="file" accept="application/json,.json" data-mutation disabled></label></div><details><summary>或粘贴修改方案</summary><label for="edit-proposal-json">修改方案 JSON</label><textarea id="edit-proposal-json" class="code-input" rows="4" data-mutation></textarea><div class="actions"><button id="apply-edit-proposal" data-mutation disabled>校验并应用修改</button></div></details></section>
<section class="card"><h3>属性与补丁</h3><form id="editor-form"><fieldset id="editor-fields" disabled><label for="edit-title">面板标题</label><input id="edit-title" maxlength="120" data-mutation><label for="edit-row">选择设置行</label><select id="edit-row" data-mutation></select><label for="edit-label">行标签</label><input id="edit-label" maxlength="120" data-mutation><label class="checkline"><input id="edit-enabled" type="checkbox" data-mutation>启用控件</label><div id="initial-field"></div><p id="action-description" class="hint"></p><p class="initial-note">保留当前试玩值；新默认值在恢复默认时生效。</p><div class="actions"><button id="apply-edit" type="submit" class="primary" data-mutation>应用修改</button></div></fieldset></form><details><summary>补丁与修改记录</summary><label for="patch-json">按稳定 ID 修改的 Patch JSON</label><textarea id="patch-json" class="code-input" rows="4" data-mutation></textarea><div class="actions"><button id="apply-json-patch" data-mutation disabled>应用补丁</button><button id="download-patch" disabled>导出最后补丁</button></div><ol id="history-list"></ol></details><div class="actions"><button id="download-spec" disabled>导出面板方案</button></div></section></div>
<section class="card"><details><summary>Unity 导出与接入</summary><p id="unity-export-help" class="hint">ZIP 包含当前面板、试玩值、引用图片和 Unity 适配脚本。解压后在 Unity 6 / UGUI 2.0 中创建 Prefab；需要项目字体及 EventSystem。下载后仍需在 Unity 中验证。</p></details><details><summary>事件与校验证据</summary><pre id="event-output">尚未操作</pre><pre id="evidence-output"></pre></details><details><summary>当前试玩状态</summary><dl id="live-state"><dt>尚未载入</dt><dd>—</dd></dl></details></section>
</section></main>
<dialog id="saved-history" aria-labelledby="saved-history-title"><div class="dialog-head"><h2 id="saved-history-title">历史版本与本机存档</h2><button id="close-saved-history" type="button">关闭</button></div>
<p class="hint">自动保存草稿、面板与试玩值，最多保留 8 个版本；图片较大时会减少版本数。仅当前浏览器与地址可用，清理浏览器数据后会丢失，请用「导出当前面板」长期备份。恢复版本不会调用模型；本次会话的撤销记录不跨刷新保留。</p>
<p id="storage-dialog-status" class="error" role="status"></p><p id="saved-history-empty" class="hint feedback">尚无已保存面板，需求草稿会自动保存。</p><ul id="saved-versions" class="saved-versions"></ul>
<details><summary>存档维护</summary><p class="hint">重新读取会替换当前工作，请先导出尚未保存的面板。</p><div class="actions"><button id="reload-saved-history" type="button" data-mutation>重新读取本机存档</button><button id="backup-saved-history" type="button">下载存档备份</button></div><button id="reset-saved-history" type="button" data-mutation>重置本机存档</button><div id="reset-saved-confirm" hidden><p class="error">将删除本地址的历史记录，并以当前工作重新开始保存。请先备份。</p><button id="confirm-reset-saved" type="button" data-mutation>确认重置本机存档</button></div></details></dialog>
<script id="workbench-seed" type="application/json">${embedded}</script><script src="./workbench.js"></script></body></html>\n`;
}
