import {canonicalJson} from '../../src/canonical.mjs';
import {suiteSamples} from './fixture.mjs';
const base=`*{box-sizing:border-box}body{margin:0;background:#11161B;color:#F4F5F6;font:15px/1.6 "Segoe UI","Microsoft YaHei UI",sans-serif}main{max-width:1260px;margin:auto;padding:32px 28px}h1{font-size:26px;font-weight:500;margin:0}p{color:#B8C2C9;margin:8px 0 22px}a{color:#A6CCF4;text-decoration:none}a:focus-visible,button:focus-visible{outline:2px solid #75B8FF;outline-offset:4px}.toolbar{display:flex;flex-wrap:wrap;justify-content:space-between;gap:12px}nav{display:flex;flex-wrap:wrap;gap:6px}nav a,nav button{padding:8px 13px;border:1px solid #3C4852;border-radius:8px;font:inherit;font-size:14px;color:#BBC9D3;background:transparent;cursor:pointer}nav a[aria-current=true],nav button[aria-pressed=true]{background:#E5EDF4;border-color:#E5EDF4;color:#17222D}h2{font-size:15px;font-weight:400;margin:0 0 10px;color:#C9D2DA}.stage{min-width:0;background:#0D1216;border-radius:16px;overflow:hidden}footer{font-size:13px;color:#A1ADB8;margin-top:20px}footer p{font-size:12px;margin:7px 0}@media(max-width:800px){main{padding:22px 16px}h1{font-size:23px}nav a,nav button{padding:7px 10px;font-size:13px}}`;
const head=title=>`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>${title}</title>`;
export function comparisonHtml(entries){
  return `${head('Apple 风格 · 整套精修对比')}<style>${base}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;margin-top:22px}.grid>section{min-width:0}.canvas{width:100%;min-width:0}.panel-instance-surface{margin:auto}.delivery{margin-top:16px;text-align:right}#caption{margin-bottom:0}@media(max-width:800px){.grid{grid-template-columns:minmax(0,1fr);gap:24px}}</style>
<main><h1>Apple 风格 · 整套精修对比</h1><p>统一文字层级、完整底板与操作比例。<a href="overview.html">查看整套总览 ↗</a></p><div class="toolbar"><nav aria-label="面板类型">${suiteSamples.map(item=>`<a data-purpose="${item.id}" href="?panel=${item.id}-light">${item.title}</a>`).join('')}</nav><nav aria-label="颜色模式"><a data-mode="light" href="?panel=menu-light">浅色</a><a data-mode="dark" href="?panel=menu-dark">深色</a></nav></div><p id="caption"></p><span id="name" hidden></span><div class="grid"><section><h2>上一版 Apple 样本</h2><div class="stage" id="before-stage"><div class="canvas" id="before"></div></div></section><section><h2>统一精修</h2><div class="stage" id="after-stage"><div class="canvas" id="after"></div></div></section></div><div class="delivery"><a id="download" download>下载此样本</a></div><footer><span id="feedback" role="status">可点击按钮和调整设置，左右两份独立试玩。</span><p>本地设计候选，尚未设为默认。退出确认沿用上一轮精修。使用系统字体与现有导出链。</p></footer></main><script id="review-seed" type="application/json">${canonicalJson(entries).replaceAll('<','\\u003c')}</script><script src="review.js"></script></html>`;
}
export function overviewHtml(){
  return `${head('Apple 风格 · 整套精修')}<style>${base}.collection{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px;margin-top:24px}.collection[hidden]{display:none}.sample{min-width:0}.sample h2{display:flex;justify-content:space-between;margin-bottom:8px}.sample h2 span{color:#8EADD0;font-size:13px}.sample img{display:block;width:100%;height:300px;object-fit:contain;background:#0D1216;border-radius:14px}.sample p{font-size:13px;margin:9px 0 0}.sample a:hover img{outline:1px solid #718CA5}.sample a:focus-visible{display:block;border-radius:14px}@media(max-width:1000px){.collection{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.collection{grid-template-columns:minmax(0,1fr)}.sample img{height:320px}}</style>
<main><h1>Apple 风格 · 整套精修</h1><p>先看六类面板的整体关系，点击任一面板可与上一版并排比较、试玩和下载。</p><nav aria-label="颜色模式"><button data-mode="light" aria-pressed="true">浅色</button><button data-mode="dark" aria-pressed="false">深色</button></nav>${['light','dark'].map(mode=>`<div class="collection" data-collection="${mode}" ${mode==='dark'?'hidden':''}>${suiteSamples.map(sample=>`<section class="sample"><a href="index.html?panel=${sample.id}-${mode}"><h2>${sample.title}<span>对比试玩 ↗</span></h2><img src="${sample.id}-${mode}.png" alt="${mode==='light'?'浅色':'深色'}${sample.title}精修样本" width="540" height="660"></a><p>${sample.caption}</p></section>`).join('')}</div>`).join('')}<footer><p>实际 Pixi 渲染截图；进入对比页后可操作。使用 Segoe UI / Microsoft YaHei UI 系统字体。此组为本地候选，尚未推广默认。</p></footer></main><script>const buttons=[...document.querySelectorAll('[data-mode]')],collections=[...document.querySelectorAll('[data-collection]')];function mode(value){for(const button of buttons)button.setAttribute('aria-pressed',String(button.dataset.mode===value));for(const collection of collections)collection.hidden=collection.dataset.collection!==value;history.replaceState(null,'','?mode='+value);}for(const button of buttons)button.addEventListener('click',()=>mode(button.dataset.mode));mode(new URL(location.href).searchParams.get('mode')==='dark'?'dark':'light');</script></html>`;
}
