import { test, expect } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { assetsPackageFixture } from '../helpers/assets-package-fixture.ts';
import { componentHandoffEntries } from '../../src/decomposition-import.ts';
import { importComponentHandoffWithReview } from '../../src/component-handoff.ts';

const json = (name:string,value:unknown)=>({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
test('single v2 materials: default, real pointer/key, save/reopen, Studio ZIP and official CLI roundtrip',async({page,context},info)=>{
  const f=await assetsPackageFixture();let modelCalls=0;
  await context.route('**/api/ui-vision**',route=>{modelCalls++;return route.abort();});
  await page.goto('/');
  await page.locator('#open-bundle').setInputFiles(json('reviewed-fixture-target.json',f.target));
  await expect(page.locator('#appearance-target')).toBeEnabled();await page.locator('#appearance-target').click();
  await page.locator('#decomposition-file').setInputFiles({name:'assets-v2.zip',mimeType:'application/zip',buffer:Buffer.from(f.bytes)});
  await expect(page.locator('#decomposition-status')).toContainText('单包 v2');
  await expect(page.locator('#decomposition-status')).toContainText('仍需用户业务需求');
  await page.locator('#appearance-file').setInputFiles(json('explicit-fixture-binding.json',f.binding));
  await expect(page.locator('#appearance-apply')).toBeEnabled();await page.locator('#appearance-apply').click();
  await expect(page.locator('#appearance-status')).toContainText('已确定性应用');
  const canvas=page.locator('#main-preview canvas');await expect(canvas).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>window.uiStudio.snapshot().views[0].inspection.nodes.find(n=>n.id==='apply-switch')?.value)).toBe(false);
  await canvas.screenshot({path:info.outputPath('01-default-before-input.png')});
  const box=await canvas.boundingBox();expect(box).toBeTruthy();
  await page.mouse.click(box!.x+90/500*box!.width,box!.y+90/400*box!.height);
  await expect.poll(()=>page.evaluate(()=>window.uiStudio.snapshot().views[0].inspection.nodes.find(n=>n.id==='apply-switch')?.value)).toBe(true);
  await canvas.focus();
  for(let i=0;i<3 && await canvas.getAttribute('data-focused-component')!=='apply-switch';i++)await page.keyboard.press('Tab');
  await expect(canvas).toHaveAttribute('data-focused-component','apply-switch');await page.keyboard.press('Space');
  await expect.poll(()=>page.evaluate(()=>window.uiStudio.snapshot().views[0].inspection.nodes.find(n=>n.id==='apply-switch')?.value)).toBe(false);
  const snap=await page.evaluate(()=>window.uiStudio.snapshot());
  expect(snap.views[0].events.some(e=>e.type==='change'&&e.source==='mouse')).toBe(true);
  expect(snap.views[0].events.some(e=>e.type==='change'&&e.source==='keyboard')).toBe(true);
  await writeFile(info.outputPath('events.json'),JSON.stringify(snap,null,2));
  const save=page.waitForEvent('download');await page.locator('#studio-export').click();const saved=info.outputPath('saved.ui-bundle.json');await(await save).saveAs(saved);
  await page.close();const reopened=await context.newPage();await reopened.goto('/');await reopened.locator('#open-bundle').setInputFiles(saved);
  await expect.poll(()=>reopened.evaluate(()=>window.uiStudio.snapshot().ready)).toBe(true);
  const exportZip=reopened.waitForEvent('download');await reopened.getByRole('button',{name:'导出交付包'}).click();const out=info.outputPath('studio-roundtrip.zip');await(await exportZip).saveAs(out);
  const bytes=await readFile(out),entries=await componentHandoffEntries(bytes);
  expect(entries.get('decomposition/assets.zip')).toEqual(f.bytes);
  const compiled=await importComponentHandoffWithReview(bytes);expect(compiled.referenceEvidence.status).toBe('missing_reference_evidence');
  const cli=fileURLToPath(new URL('../../scripts/cli.mjs',import.meta.url));
  const cliBundle=info.outputPath('cli-reimport.ui-bundle.json');
  const result=spawnSync(process.execPath,[cli,'component-handoff',out,'--output',cliBundle],{encoding:'utf8'});
  await writeFile(info.outputPath('cli-result.json'),JSON.stringify({status:result.status,stdout:result.stdout,stderr:result.stderr},null,2));expect(result.status,result.stderr).toBe(0);
  const cliZip=info.outputPath('cli-reexport.zip');const exported=spawnSync(process.execPath,[cli,'reference-export',cliBundle,'--output',cliZip],{encoding:'utf8'});expect(exported.status,exported.stderr).toBe(0);
  expect((await componentHandoffEntries(await readFile(cliZip))).get('decomposition/assets.zip')).toEqual(f.bytes);
  await reopened.locator('#open-handoff').setInputFiles(cliZip);
  await expect.poll(()=>reopened.evaluate(()=>window.uiStudio.snapshot().ready)).toBe(true);
  await reopened.locator('#main-preview canvas').screenshot({path:info.outputPath('02-cli-studio-reimport.png')});
  expect(modelCalls).toBe(0);
});
