import {test,expect,type Page} from '@playwright/test';
import {waitForWorkbenchDocument} from '../helpers/workbench-readiness.ts';
import {createBundle} from '../../src/bundle.ts';import type{UiDocument,UiNode}from'../../src/tree-contract.ts';
const style={backgroundColor:'#FFFFFF',borderColor:'#000000',borderWidth:1,cornerRadius:2,textColor:'#000000',fontFamily:'sans-serif',fontSize:14,fontWeight:'normal' as const,opacity:1};
const b=(id:string,x:number,y:number,effects:any[]):UiNode=>({id,type:'Button',layout:{x,y,width:100,height:40},props:{label:id,enabled:true,style,interaction:{version:'1.0',mode:'internal',effects}},children:[]});
const effect=(targetId:string,open:boolean)=>({kind:'dialog-open',targetId,open});
function modalFixture():UiDocument{return{schemaVersion:'0.2',id:'modal-navigation-fixture',canvas:{width:600,height:400},root:{id:'root',type:'Container',layout:{x:0,y:0,width:600,height:400},props:{style},children:[b('base-open',10,10,[effect('details',true)]),{id:'details',type:'Dialog',layout:{x:130,y:40,width:400,height:280},props:{open:true,title:'Details',modal:true,backdrop:{color:'#000000',opacity:0},style},children:[b('notice-open',20,70,[effect('notice',true)]),b('details-close',20,190,[effect('notice',false),effect('details',false)])]},{id:'notice',type:'Dialog',layout:{x:340,y:150,width:240,height:220},props:{open:true,title:'Notice',modal:true,backdrop:{color:'#000000',opacity:0},style},children:[b('notice-close',10,90,[effect('notice',false)]),b('notice-cross',120,90,[effect('notice',false)])]}]}};}
const snapshot=(p:Page)=>p.evaluate(()=>window.uiHarness.inspect());
const click=async(p:Page,id:string)=>{const n=(await snapshot(p)).nodes.find(n=>n.id===id)!,box=await p.locator('#canvas-host canvas').boundingBox();if(!box)throw Error('canvas');const d=await p.evaluate(()=>window.uiHarness.getDocument()) as UiDocument;await p.mouse.click(box.x+(n.bounds.x+n.bounds.width/2)*box.width/d.canvas.width,box.y+(n.bounds.y+n.bounds.height/2)*box.height/d.canvas.height);};
const load=async(p:Page,doc:UiDocument)=>{await p.goto('/workbench.html');await p.waitForFunction(()=>Boolean(window.uiHarness));const bundle=await createBundle(doc,[],{kind:'programmatic-fixture',description:'Actual modal keyboard ownership and List selection visibility regression.'});await p.locator('#bundle-file').setInputFiles({name:'navigation.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bundle))});await waitForWorkbenchDocument(p,doc.id);};
test('transparent top modal blocks real pointer input and wraps Tab and Shift+Tab',async({page})=>{
 await load(page,modalFixture());await click(page,'notice-open');expect(await page.evaluate(()=>window.uiHarness.activationCount('notice-open'))).toBe(0);await click(page,'base-open');expect(await page.evaluate(()=>window.uiHarness.activationCount('base-open'))).toBe(0);
 const canvas=page.locator('#canvas-host canvas');await canvas.focus();for(const key of ['Tab','Tab','Tab','Tab','Shift+Tab','Shift+Tab','Shift+Tab']){await page.keyboard.press(key);expect(['notice-close','notice-cross']).toContain(await canvas.getAttribute('data-focused-component'));}
});
test('actual layered openers receive focus after child and parent close',async({page})=>{
 await load(page,modalFixture());await click(page,'notice-close');await click(page,'details-close');await click(page,'base-open');await expect(page.locator('#canvas-host canvas')).toHaveAttribute('data-focused-component','notice-open');await click(page,'notice-open');await expect(page.locator('#canvas-host canvas')).toHaveAttribute('data-focused-component','notice-close');await click(page,'notice-cross');await expect(page.locator('#canvas-host canvas')).toHaveAttribute('data-focused-component','notice-open');await click(page,'details-close');await expect(page.locator('#canvas-host canvas')).toHaveAttribute('data-focused-component','base-open');
});
test('keyboard List endpoint selection scrolls into its real ancestor viewport',async({page})=>{
 const doc:UiDocument={schemaVersion:'0.2',id:'list-navigation-fixture',canvas:{width:300,height:200},root:{id:'scroll',type:'ScrollView',layout:{x:0,y:0,width:280,height:120},props:{scrollX:0,scrollY:0,contentWidth:280,contentHeight:480,style},children:[{id:'list',type:'List',layout:{x:0,y:0,width:260,height:480},props:{selectedId:'r1',items:Array.from({length:12},(_,i)=>({id:'r'+(i+1),label:'Row '+(i+1)})),itemTemplate:'text-row',itemHeight:40,enabled:true,style},children:[]}]}};
 await load(page,doc);const canvas=page.locator('#canvas-host canvas');await canvas.focus();for(let i=0;i<4&&await canvas.getAttribute('data-focused-component')!=='list';i++)await page.keyboard.press('Tab');await expect(canvas).toHaveAttribute('data-focused-component','list');await page.keyboard.press('End');expect((await snapshot(page)).nodes.find(n=>n.id==='list')!.value).toBe('r12');expect((await snapshot(page)).nodes.find(n=>n.id==='scroll')!.value).toEqual({x:0,y:360});await page.keyboard.press('Home');expect((await snapshot(page)).nodes.find(n=>n.id==='scroll')!.value).toEqual({x:0,y:0});
});
