import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {core,nodesOf} from './helpers.mjs';
import {createPanelBundle,validatePanelBundle} from '../src/panel-bundle.mjs';
import {createUnityDocument} from '../src/unity-export.mjs';
import {attachPanelSession} from '../src/state.mjs';
import {createApplePanelSample} from '../examples/apple-panel-samples-v1/fixture.mjs';
import {polishAppleDialog} from '../examples/apple-dialog-polish-v1/fixture.mjs';
const json=async path=>JSON.parse(await readFile(new URL(path,import.meta.url),'utf8'));
const minimal=await json('../examples/modern-minimal.catalog.json');
// A valid public catalog supplies the theme; the sample factory's source guard is separately covered.
for(const mode of ['light','dark'])test(`polished ${mode} confirmation is compact, complete and business-exact`,async()=>{
  const catalog=structuredClone(minimal),theme=catalog.themes.find(theme=>theme.id===`modern-mint-${mode}`);
  Object.assign(theme,{surfaceStyle:'grouped-v1',iconStyle:'plain-v1',sliderStyle:'raised-v1'});
  Object.assign(theme.tokens,{fontFamily:'Segoe UI, Microsoft YaHei UI, sans-serif',fontSize:17,headingSize:17,titleSize:32,radius:14});
  const base=await json('../examples/audio-settings.panel.json');
  const source={compilerVersion:'0.23.0',spec:{...base,theme:{id:theme.id,version:theme.version},provenance:{kind:'programmatic-fixture'},layout:{width:500,padding:28,gap:24,sectionGap:20,labelWidth:112,rowHeight:56,titleHeight:44,sectionTitleHeight:24,maxHeight:420,overflow:'error'}},catalog};
  const sample=createApplePanelSample('exit',mode,source,minimal),before=await createPanelBundle(sample.after.spec,sample.after.catalog,core);
  const snapshot=structuredClone(before),input=polishAppleDialog(before),after=await createPanelBundle(input.spec,input.catalog,core);
  await validatePanelBundle(before,core);await validatePanelBundle(after,core);assert.deepEqual(before,snapshot);
  for(const key of ['state','bindings','actions','assetClosure'])assert.deepEqual(after[key],before[key]);
  assert.deepEqual(after.spec.sections.flatMap(section=>section.rows),before.spec.sections.flatMap(section=>section.rows));
  assert.equal(after.compilerVersion,'0.18.0');
  const beforeNodes=nodesOf(before.componentBundle.document),nodes=nodesOf(after.componentBundle.document),node=id=>nodes.find(node=>node.id===`sample-exit.${id}`);
  assert(node('panel').layout.width<beforeNodes.find(node=>node.id==='sample-exit.panel').layout.width);
  assert(node('panel').layout.height<beforeNodes.find(node=>node.id==='sample-exit.panel').layout.height);
  assert(node('panel').layout.height<=280,'the compact dialog must eliminate surplus vertical space');
  assert.notEqual(node('panel').props.style.backgroundColor,node('canvas').props.style.backgroundColor);
  assert(node('panel-shadow.0'));assert.equal(node('panel').props.style.cornerRadius,20);
  assert.equal(node('row.cancel.control').layout.width,node('row.confirm.control').layout.width);
  const positions=new Map();
  const visit=(node,x=0,y=0)=>{const position={x:x+node.layout.x,y:y+node.layout.y};positions.set(node.id,position);for(const child of node.children??[])visit(child,position.x,position.y);};
  visit(after.componentBundle.document.root);
  assert.equal(positions.get('sample-exit.row.cancel.control').y,positions.get('sample-exit.row.confirm.control').y,'dialog actions belong on one line');
  assert(node('row.cancel.control').layout.height>=44);
  const runtime={getDocument:()=>after.componentBundle.document,subscribe:()=>()=>{},setValue:()=>{},setVisible:()=>{},setEnabled:()=>{}};
  attachPanelSession(after.spec,runtime,()=>{},after.state,'focused-v1').destroy();
  const unity=await createUnityDocument(after,core);assert.equal(unity.controls.length,2);
  before.spec.provenance.kind='agent-authored';assert.throws(()=>polishAppleDialog(before),/DIALOG_POLISH_FIXTURE_ONLY/);
});
