import test from 'node:test';
import assert from 'node:assert/strict';
import {core,fixture,catalog} from './helpers.mjs';
import {readJson} from '../src/io.mjs';
import {formRequest,formIntent} from '../examples/forms-v1/fixture.mjs';
import {createPlanningContext} from '../src/planning-context.mjs';
import {materializePanelIntent} from '../src/panel-intent.mjs';
import {createPanelBundle} from '../src/panel-bundle.mjs';
import {createPanelHost} from '../src/panel-host.mjs';
import {projectPanelEvent} from '../src/state.mjs';
import {controlId} from '../src/compiler.mjs';
import {createMemoryGamePort} from '../src/game-port.mjs';
import {validateGameBinding,attachPanelGameBinding} from '../src/game-binding.mjs';
const audio=await createPanelBundle(fixture,catalog,core),formCatalog=await readJson(new URL('../examples/modern-mint-forms.catalog.json',import.meta.url)),context=await createPlanningContext(formRequest,formCatalog),form=await createPanelBundle((await materializePanelIntent(context,formIntent(context))).spec,formCatalog,core);
const binding=(bundle,states=[],commands=[])=>({gameBindingVersion:'0.1',panelId:bundle.spec.id,panelSha256:bundle.sha256,states,commands}),audioBinding=binding(audio,[{fieldId:'volume',key:'volume',direction:'two-way'},{fieldId:'audioEnabled',key:'enabled',direction:'two-way'}]),formBinding=(concurrency='drop')=>binding(form,[{fieldId:'row0',key:'draft',direction:'to-game'}],[{rowId:'row1',command:'save',payload:{name:'row0'},concurrency}]);
const gate=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
async function setup(bundle=audio){const mounts=new Map(),host=createPanelHost({core,mount:async input=>{let state=structuredClone(input.state);const adapter={getState:()=>structuredClone(state),setState:next=>{state=structuredClone(next);},inspect:()=>({instances:1,resources:1,externalListeners:1,nodes:[]}),destroy(){}};mounts.set(input.instanceId,{user(rowId,type,value){const projected=projectPanelEvent(bundle.spec,state,{id:controlId(bundle.spec.id,rowId),type,source:'keyboard',value});state=projected.state;if(projected.event)input.onEvent(projected.event);}});return adapter;}}),panel=await host.add('a',bundle);return{host,panel,user:(...args)=>mounts.get('a').user(...args)};}
const connect=(fixture,port,route=audioBinding,extra={})=>attachPanelGameBinding({host:fixture.host,instanceId:'a',bundle:route.panelId===audio.spec.id?audio:form,binding:route,port,...extra});

test('changing display labels requires a new source digest but keeps the same explicit business targets',async()=>{const renamed=structuredClone(audio.spec);renamed.sections[0].rows[0].label='任意新的文案';const updated=await createPanelBundle(renamed,catalog,core);assert.throws(()=>validateGameBinding(audioBinding,updated),/GAME_BINDING_SOURCE/);const refreshed={...audioBinding,panelSha256:updated.sha256};assert.equal(validateGameBinding(refreshed,updated).states[0].key,'volume');});

test('binding refuses stale source, unknown fields, duplicate targets and inferred directions',()=>{assert.equal(validateGameBinding(audioBinding,audio).states[0].key,'volume');for(const mutate of [r=>r.panelSha256='0'.repeat(64),r=>r.states[0].fieldId='not-a-field',r=>r.states.push(r.states[0]),r=>r.states[0].key='constructor',r=>r.states[0].direction='auto',r=>r.extra=true]){const bad=structuredClone(audioBinding);mutate(bad);assert.throws(()=>validateGameBinding(bad,audio));}});
test('initial game hydration is silent and rejects invalid game state before subscribing or writing',async()=>{const f=await setup(),port=createMemoryGamePort({initialState:{volume:30,enabled:false}}),bridge=connect(f,port);assert.deepEqual(f.panel.getState(),{volume:30,audioEnabled:false});assert.equal(bridge.inspect().started,0);bridge.destroy();assert.equal(port.inspect().subscribers,0);assert.equal(f.host.inspect().subscribers,0);const invalid=createMemoryGamePort({initialState:{volume:101,enabled:false}}),before=f.panel.getState();assert.throws(()=>connect(f,invalid));assert.deepEqual(f.panel.getState(),before);assert.equal(invalid.inspect().subscribers,0);f.host.destroy();port.destroy();invalid.destroy();});
test('two instances sharing a game port synchronize without echoing game updates as player actions',async()=>{const f=await setup(),b=await f.host.add('b',audio),port=createMemoryGamePort({initialState:{volume:30,enabled:true}}),aBridge=connect(f,port),bBridge=attachPanelGameBinding({host:f.host,instanceId:'b',bundle:audio,binding:audioBinding,port});let notifications=0;const detach=port.subscribe(()=>notifications++);f.user('volume-row','change',40);assert.equal(port.getSnapshot().volume,40);assert.equal(b.getState().volume,40);assert.equal(notifications,1);port.update({volume:55});assert.equal(f.panel.getState().volume,55);assert.equal(b.getState().volume,55);assert.equal(notifications,2);aBridge.destroy();bBridge.destroy();detach();assert.equal(port.inspect().subscribers,0);f.host.destroy();port.destroy();});
test('game state pushes continue while view is closed and a destroyed host detaches the bridge',async()=>{const f=await setup(),port=createMemoryGamePort({initialState:{volume:30,enabled:true}}),bridge=connect(f,port);f.panel.close();port.update({volume:42});assert.equal(f.panel.getState().volume,42);await f.panel.open();assert.equal(f.panel.getState().volume,42);f.host.destroy();port.update({volume:50});assert.equal(bridge.inspect().alive,false);assert.equal(port.inspect().subscribers,0);port.destroy();});
test('bad game pushes preserve the complete prior panel state and report an error',async()=>{const f=await setup(),port=createMemoryGamePort({initialState:{volume:30,enabled:true}}),errors=[],bridge=connect(f,port,audioBinding,{onError:e=>errors.push(e)}),before=f.panel.getState();port.update({volume:40,enabled:'wrong'});assert.deepEqual(f.panel.getState(),before);assert.equal(errors.length,1);bridge.destroy();f.host.destroy();port.destroy();});
test('a synchronous game update rejection retains the draft and does not invent a business success',async()=>{const f=await setup(),errors=[],port=createMemoryGamePort({initialState:{volume:30,enabled:true},validate:state=>{if(state.volume>50)throw Error('restricted');}}),bridge=connect(f,port,audioBinding,{onError:e=>errors.push(e)});f.user('volume-row','change',60);assert.equal(f.panel.getState().volume,60);assert.equal(port.getSnapshot().volume,30);assert.equal(errors[0].code,'GAME_STATE_WRITE_FAILED');bridge.destroy();f.host.destroy();port.destroy();});
test('submit snapshots preserve raw Unicode text and invalid form cannot invoke the business command',async()=>{const f=await setup(form),calls=[],port=createMemoryGamePort({initialState:{draft:'',saved:''},commands:{save:async(payload,ctx)=>{calls.push(payload);ctx.update({saved:payload.name});}}}),bridge=connect(f,port,formBinding());assert.equal((await bridge.run('row1')).status,'BLOCKED');assert.equal(calls.length,0);f.user('row0','change',' 甲😀 ');assert.equal((await bridge.run('row1')).status,'COMPLETE');assert.deepEqual(calls,[{name:' 甲😀 '}]);assert.equal(port.getSnapshot().saved,' 甲😀 ');bridge.destroy();f.host.destroy();port.destroy();});
test('drop concurrency accepts one submission and does not repeat the command',async()=>{const f=await setup(form),wait=gate();let calls=0;const port=createMemoryGamePort({initialState:{draft:''},commands:{save:async()=>{calls++;await wait.promise;}}}),bridge=connect(f,port,formBinding());f.user('row0','change','角色甲');const first=bridge.run('row1');assert.equal((await bridge.run('row1')).status,'DROPPED');assert.equal(calls,1);wait.resolve();assert.equal((await first).status,'COMPLETE');assert.equal(bridge.inspect().dropped,1);bridge.destroy();f.host.destroy();port.destroy();});
test('replace concurrency cancels old commits even if its handler ignores the signal until after awaiting',async()=>{const f=await setup(form),wait=gate();let calls=0;const port=createMemoryGamePort({initialState:{draft:'',saved:''},commands:{save:async(payload,ctx)=>{if(++calls===1)await wait.promise;ctx.update({saved:payload.name});}}}),bridge=connect(f,port,formBinding('replace'));f.user('row0','change','旧角色');const old=bridge.run('row1');f.user('row0','change','新角色');assert.equal((await bridge.run('row1')).status,'COMPLETE');wait.resolve();assert.equal((await old).status,'CANCELLED');assert.equal(port.getSnapshot().saved,'新角色');assert.equal(bridge.inspect().pending,0);bridge.destroy();f.host.destroy();port.destroy();});
test('failed async submit keeps draft and prior business record, and only explicit retry starts another call',async()=>{const f=await setup(form),errors=[];let calls=0;const port=createMemoryGamePort({initialState:{draft:'',saved:'既有角色'},commands:{save:async(payload,ctx)=>{if(++calls===1){const error=Error('rejected');error.code='ROLE_NAME_EXISTS';throw error;}ctx.update({saved:payload.name});}}}),bridge=connect(f,port,formBinding(),{onError:e=>errors.push(e)});f.user('row0','change','新角色');assert.equal((await bridge.run('row1')).status,'FAILED');await Promise.resolve();assert.equal(calls,1);assert.equal(f.panel.getState().row0,'新角色');assert.equal(port.getSnapshot().saved,'既有角色');assert.equal(errors[0].code,'ROLE_NAME_EXISTS');assert.equal((await bridge.run('row1')).status,'COMPLETE');assert.equal(calls,2);assert.equal(port.getSnapshot().saved,'新角色');bridge.destroy();f.host.destroy();port.destroy();});
test('destroy during an async command aborts it, removes both subscriptions and prevents late writes',async()=>{const f=await setup(form),wait=gate(),port=createMemoryGamePort({initialState:{draft:'',saved:''},commands:{save:async(payload,ctx)=>{await wait.promise;ctx.update({saved:payload.name});}}}),bridge=connect(f,port,formBinding());f.user('row0','change','角色甲');const command=bridge.run('row1');bridge.destroy();bridge.destroy();assert.equal(port.inspect().subscribers,0);assert.equal(f.host.inspect().subscribers,0);wait.resolve();assert.equal((await command).status,'CANCELLED');assert.equal(port.getSnapshot().saved,'');assert.equal(port.inspect().pending,0);f.host.destroy();port.destroy();});
test('snapshots and listeners cannot mutate the stored game state; invalid updates are atomic',()=>{const port=createMemoryGamePort({initialState:{x:1,y:true},validate:s=>{if(typeof s.y!=='boolean')throw Error('type');}}),seen=[];port.subscribe(value=>{value.x=999;throw Error('subscriber');});port.subscribe(value=>seen.push(value));const snapshot=port.getSnapshot();snapshot.x=900;port.update({x:2});assert.equal(port.getSnapshot().x,2);assert.equal(seen[0].x,2);assert.throws(()=>port.update({x:3,y:'bad'}));assert.equal(port.getSnapshot().x,2);assert.throws(()=>port.update({unknown:1}));port.destroy();assert.equal(port.inspect().subscribers,0);});
test('port destruction prevents delayed handler commits and releases subscriptions',async()=>{const wait=gate(),port=createMemoryGamePort({initialState:{x:1},commands:{save:async(_,ctx)=>{await wait.promise;ctx.update({x:2});}}});port.subscribe(()=>{});const pending=port.invoke('save',{});port.destroy();port.destroy();wait.resolve();await assert.rejects(pending,error=>error.name==='AbortError');assert.deepEqual(port.inspect(),{alive:false,pending:0,subscribers:0});});
