import test from 'node:test';
import assert from 'node:assert/strict';
import {core,fixture,catalog} from './helpers.mjs';
import {createPanelBundle} from '../src/panel-bundle.mjs';
import {createPanelHost} from '../src/panel-host.mjs';
const bundle=await createPanelBundle(fixture,catalog,core);
function driver(){const mounts=[];const mount=async input=>{const item={input,state:structuredClone(input.state),destroyed:0,writeFailure:false};mounts.push(item);return{getState:()=>structuredClone(item.state),setState:value=>{if(item.writeFailure)throw Error('renderer-write-failed');item.state=structuredClone(value);},inspect:()=>({instances:1,externalListeners:2,resources:1,nodes:[]}),destroy:()=>{item.destroyed++;}};};return{mount,mounts};}
test('same source mounts twice with independent values and instance-bound events',async()=>{const d=driver(),events=[],host=createPanelHost({core,mount:d.mount,onEvent:e=>events.push(e)}),a=await host.add('first',bundle),b=await host.add('second',bundle);a.setState({...a.getState(),volume:30});assert.equal(b.getState().volume,80);d.mounts[0].input.onEvent({name:'volume',value:30});assert.equal(events.length,1);assert.equal(events[0].instanceId,'first');assert.equal(events[0].panelId,bundle.spec.id);host.destroy();});
test('close preserves current values, detaches old adapter and reopen hydrates silently',async()=>{const d=driver(),events=[],host=createPanelHost({core,mount:d.mount,onEvent:e=>events.push(e)}),a=await host.add('panel',bundle);a.setState({...a.getState(),volume:35});a.close();assert.equal(d.mounts[0].destroyed,1);assert.equal(a.status,'CLOSED');assert.equal(a.inspect().resources,0);a.setState({...a.getState(),volume:45});await a.open();assert.equal(a.getState().volume,45);assert.equal(d.mounts[1].input.state.volume,45);assert.equal(events.length,0);d.mounts[0].input.onEvent({name:'stale'});assert.equal(events.length,0);host.destroy();});
test('repeated opens mount once and destruction is idempotent with no late callbacks',async()=>{const d=driver(),host=createPanelHost({core,mount:d.mount}),a=await host.add('panel',bundle);await Promise.all([a.open(),a.open()]);assert.equal(d.mounts.length,1);a.destroy();a.destroy();assert.equal(d.mounts[0].destroyed,1);assert.equal(host.get('panel'),undefined);assert.throws(()=>a.getState(),/INSTANCE_DESTROYED/);host.destroy();host.destroy();assert.equal(host.inspect().instances.length,0);assert.throws(()=>host.get('panel'),/HOST_DESTROYED/);});
test('invalid state is atomically refused and another panel remains usable',async()=>{const d=driver(),host=createPanelHost({core,mount:d.mount}),a=await host.add('a',bundle),b=await host.add('b',bundle),before=a.getState();assert.throws(()=>a.setState({...before,volume:101}));assert.deepEqual(a.getState(),before);assert.equal(b.getState().volume,80);assert.throws(()=>a.setProgress('volume',10),/PROGRESS_FIELD/);host.destroy();});
test('one failing callback cannot mutate delivery to a later callback or break another instance',async()=>{const d=driver(),errors=[],later=[],host=createPanelHost({core,mount:d.mount,onError:e=>errors.push(e)});host.subscribe(e=>{e.event.name='mutated';throw Error('callback-failed');});host.subscribe(e=>later.push(e));const a=await host.add('a',bundle);d.mounts[0].input.onEvent({name:'original'});assert.equal(later[0].event.name,'original');assert.deepEqual(errors,[{instanceId:'a',code:'PANEL_HOST_CALLBACK_ERROR'}]);assert.equal(a.status,'OPEN');host.destroy();});
test('duplicate IDs and tampered bundles are refused without mounting or replacing existing state',async()=>{const d=driver(),host=createPanelHost({core,mount:d.mount}),a=await host.add('a',bundle);await assert.rejects(host.add('a',bundle),/INSTANCE_EXISTS/);const bad=structuredClone(bundle);bad.spec.title='tampered';await assert.rejects(host.add('bad',bad));assert.equal(d.mounts.length,1);assert.equal(host.get('bad'),undefined);assert.deepEqual(a.getState(),bundle.state);host.destroy();});
test('destroy during pending mount releases late completion and prevents instance resurrection',async()=>{const d=driver();let finish,started;const ready=new Promise(r=>started=r),gate=new Promise(r=>finish=r),host=createPanelHost({core,mount:async input=>{started();await gate;return d.mount(input);}});const adding=host.add('a',bundle);await ready;host.destroy();finish();await assert.rejects(adding,/OPEN_CANCELLED/);assert.equal(d.mounts[0].destroyed,1);assert.equal(host.inspect().instances.length,0);});
test('close during reopen can be followed by a new open without adopting the stale adapter',async()=>{let finish;const gate=new Promise(r=>finish=r),d=driver(),host=createPanelHost({core,mount:async input=>{if(d.mounts.length===1)await gate;return d.mount(input);}}),r=await host.add('r',bundle);r.close();const opening=r.open();r.close();finish();await assert.rejects(opening,/OPEN_CANCELLED/);assert.equal(r.status,'CLOSED');await r.open();assert.equal(r.status,'OPEN');assert.equal(d.mounts[1].destroyed,1);host.destroy();});
test('renderer failure releases only its instance and other live instances still work',async()=>{const d=driver(),host=createPanelHost({core,mount:d.mount}),a=await host.add('a',bundle),b=await host.add('b',bundle);d.mounts[0].writeFailure=true;assert.throws(()=>a.setState({...a.getState(),volume:30}),/renderer-write-failed/);assert.equal(a.status,'ERROR');assert.equal(d.mounts[0].destroyed,1);b.setState({...b.getState(),volume:25});assert.equal(b.getState().volume,25);host.destroy();});
test('host destruction cleans every instance even when one renderer cleanup fails',async()=>{const d=driver(),host=createPanelHost({core,mount:async input=>{const adapter=await d.mount(input);if(input.instanceId==='bad')return{...adapter,destroy(){adapter.destroy();throw Error('cleanup-failed');}};return adapter;}});await host.add('bad',bundle);await host.add('good',bundle);assert.throws(()=>host.destroy(),/CLEANUP_FAILED/);assert(d.mounts.every(m=>m.destroyed===1));assert.equal(host.inspect().instances.length,0);});
test('export preserves authored defaults and current state instead of baking trial values into defaults',async()=>{const d=driver(),host=createPanelHost({core,mount:d.mount}),a=await host.add('a',bundle);a.setState({...a.getState(),volume:25});a.close();const exported=await a.exportBundle();assert.equal(exported.spec.state.find(f=>f.id==='volume').initial,80);assert.equal(exported.state.volume,25);host.destroy();});
